name: release
on:
  push:
    tags: ["v*.*.*"]
env:
  REGISTRY: ghcr.io
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Lowercase repo owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
      - name: Setup Node & pnpm
        run: |
          corepack enable
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.repo.outputs.owner_lc }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push strategy
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/strategy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.owner_lc }}/dlmm-strategy:${{ github.ref_name }}
            ghcr.io/${{ steps.repo.outputs.owner_lc }}/dlmm-strategy:latest
      - name: Build & push bot
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/bot/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.owner_lc }}/dlmm-bot:${{ github.ref_name }}
            ghcr.io/${{ steps.repo.outputs.owner_lc }}/dlmm-bot:latest
